#!/bin/sh
##Automatically defined items##

#Vulnerability Discussion
#The log files generated by rsyslog contain valuable information regarding system configuration, user authentication, and other such information. Log files should be protected from unauthorized access.

#STIG Identification
GrpID="V-38518"
GrpTitle="SRG-OS-000206"
RuleID="SV-50319r2_rule"
STIGID="RHEL-06-000133"
Results="./Results/$GrpID"

#Remove File if already there
[ -e $Results ] && rm -rf $Results

#Setup Results File
echo $GrpID >> $Results
echo $GrpTitle >> $Results
echo $RuleID >> $Results
echo $STIGID >> $Results
##END of Automatic Items##

###Check###
scorecheck=0

for fn in $(grep -v "^#" /etc/rsyslog.conf | grep -v "^#" /etc/rsyslog.conf | sed s/^[^\/]*// | grep "^/" | cut -f1 -d" "); do 
 if [ -e $fn ]; then 
  stat -c %n-%U $fn >> $Results
 if [ "$(stat -c %U $fn)" != "root" ]; then
  ((scorecheck+=1))
  fi
 fi
done

if [ "$scorecheck" != 0 ]; then
 echo "Fail" >> $Results 
else 
 echo "Pass" >> $Results
fi